# Generated by Django 4.0.6 on 2022-08-03 02:20

from django.db import migrations, models

from board.utils.gen_master_data import gen_master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='보드 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
            ],
            options={
                'db_table': 'board',
            },
        ),
        migrations.RunPython(gen_master),
    ]
